function project = initIGREE()

project.name = "IGREE";

% ------- dir
project.dir.scripts = fileparts(mfilename('fullpath')); % -> matlab scripts
[project.dir.root, ~] = fileparts(project.dir.scripts);
project.dir.data = fullfile(project.dir.root, 'data');

% ------- other configs
project.useChannels = { ...
'FP1', 'FP2', ...
'AF7', 'AF3', 'AFZ', 'AF4', 'AF8', ...
'F7', 'F5', 'F3', 'F1', 'FZ', 'F2', 'F4', 'F6', 'F8', ...
'FT9', 'FT7', 'FC5', 'FC3', 'FC1', 'FCZ', 'FC2', 'FC4', 'FC6', 'FT8', 'FT10', ...
'T7', 'C5', 'C3', 'C1', 'CZ', 'C2', 'C4', 'C6', 'T8', ...
'TP7', 'CP5', 'CP3', 'CP1', 'CPZ', 'CP2', 'CP4', 'CP6', 'TP8', ...
'P9', 'P7', 'P5', 'P3', 'P1', 'PZ', 'P2', 'P4', 'P6', 'P8', 'P10', ...
'PO7', 'PO3', 'POZ', 'PO4', 'PO8', ...
'O1', 'OZ', 'O2' ...
'VEO','HEO' ...
};

% ------- addpath dir
addpath(genpath(project.dir.scripts));
rmpath('zx_local_archive')

end