function project = initIGREE()

project.name = "IGREE";

% ------- dir
project.dir.scripts = fileparts(mfilename('fullpath')); % -> matlab scripts
[project.dir.root, ~] = fileparts(project.dir.scripts);
project.dir.data = fullfile(project.dir.root, 'data');

% ------- other configs
project.useChannels = { ...
'FP1', 'FP2', ...
'AF7', 'AF3', 'AFZ', 'AF4', 'AF8', ...
'F7', 'F5', 'F3', 'F1', 'FZ', 'F2', 'F4', 'F6', 'F8', ...
'FT9', 'FT7', 'FC5', 'FC3', 'FC1', 'FCZ', 'FC2', 'FC4', 'FC6', 'FT8', 'FT10', ...
'T7', 'C5', 'C3', 'C1', 'CZ', 'C2', 'C4', 'C6', 'T8', ...
'TP7', 'CP5', 'CP3', 'CP1', 'CPZ', 'CP2', 'CP4', 'CP6', 'TP8', ...
'P9', 'P7', 'P5', 'P3', 'P1', 'PZ', 'P2', 'P4', 'P6', 'P8', 'P10', ...
'PO7', 'PO3', 'POZ', 'PO4', 'PO8', ...
'O1', 'OZ', 'O2' ...
'VEO','HEO' ...
};

project.brainRegions = { ...
'Frontal',  {'Fp1','Fp2','AF3','AF4','AF7','AF8','F1','F2','F3','F4','F5','F6','F7','F8','FC1','FC2','FC3','FC4','FC5','FC6'}; ...
'Central',  {'C1','C2','C3','C4','C5','C6','Cz'}; ...
'Parietal', {'P1','P2','P3','P4','P5','P6','P7','P8','Pz','CP1','CP2','CP3','CP4','CP5','CP6','CPz'}; ...
'Temporal', {'FT7','FT8','T7','T8','TP7','TP8'}; ...
'Occipital', {'O1','O2','Oz','PO3','PO4','PO7','PO8','POz'} ...
};


% ------- addpath dir
addpath(genpath(project.dir.scripts));


% *************************************************************************

% ALAN LAPTOP STUFF, won't throw error if otherwise
% ------- remove zx_local_archive dir
try rmpath(fullfile(project.dir.scripts, 'zx_local_archive')); catch, end


end